apiVersion: v1
kind: Service
metadata:
  name: sample-svc
  labels: 
   app: sample-app
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30006
    protocol: TCP
  selector:
    app: sample-app
