FROM centos

MAINTAINER srinuchikalavalasa@gmail.com

RUN mkdir /opt/tomcat/

WORKDIR /opt/tomcat

RUN curl -O https://downloads.apache.org/tomcat/tomcat-9/v9.0.33/bin/apache-tomcat-9.0.33.tar.gz
RUN tar xvfz apache*.tar.gz
RUN mv apache-tomcat*/* /opt/tomcat/.
RUN yum -y install java
RUN java -version

WORKDIR /opt/tomcat/webapps
RUN curl -O -L https://github.com/srinuchikalavalasa/project/blob/master/target/addressbook.war
RUN chmod +r addressbook.war

EXPOSE 8080

CMD ["/opt/tomcat/bin/catalina.sh", "run"]
